### PR TITLE
WIP: Error handling

### PR DESCRIPTION
**Pull request by mindriot101**
Start to implement error handling throughout.

Motivated by #7, we add error handling through the `failure` crate, adding context where possible.

This is WIP so not ready to merge yet. We need to ideally remove every:

- bare `unwrap`
- `assert!`

from the codebase.

### CODE REVIEW

**Comment by mindriot101** [comment]
I think I went a bit mad. Some of this error handling is a bit premature.

I was trying to fix #7. I have turned the assert into an error case and continued errors throughout but in fact the problem I now know is in `ContinuousView::default_x/y_range`.

Feel free to ignore or close, and a better implementation should follow.

**Comment by milliams** [comment]
This PR is pretty much what I had in mind, I just didn't have the patience at the time to go through it thoroughly like this (and also `failure` hadn't been fully released) so good work. The thing is that it's difficult to implement only a small amount of error handling so it's understandable that this has had to touch so much of the codebase.

In principle, I'd be happy to merge this as it is but if there's a different approach you want to take or you want to take a different stab at it, that's fine too.

**Comment by mindriot101** [comment]
I'm working on something (not pushed yet) that deals with #7 directly, and adds error handling in less of a scattergun approach. Bear with me!

**Comment by milliams** [comment]
Looking forward to it! :+1:

**Comment by mindriot101** [comment]
Closing in preference of #10

**Pull request closed without merging**
